export const MOCK_TEXTS: string[] = [
    `Just saw a guy at the gas station scream "$1.97?!" in joy... until he realized it was the price for gum. #inflationhits`,
    `My 2025 resolution is to check the weather *before* dressing like it's summer in the middle of a snowstorm.`,
    `BREAKING: Man finds inner peace by turning off Twitter notifications. Sources confirm he's now 87% happier.`,
    `If Mondays had a face, I'd block it.`,
    `Just once, I want my bank account to say, "You good fam" instead of sending alerts.`,
    `Dear politicians, if you can lie under oath, I should be able to lie on my resume. Fair is fair.`,
    `Imagine being a billionaire and still not tipping. Wild.`,
    `Tried manifesting a six-figure job and accidentally summoned six unpaid internships.`,
    `“Exercise is a celebration of what your body can do,” they say. My body mostly wants to sit.`,
    `Friendly reminder: Your mental health matters more than the algorithm. Log off, drink water, touch grass.`,
    `The Wi-Fi went out for 10 minutes and my family started talking to each other. Wild scenes.`,
    `Why is the weather either “hotter than the sun” or “better bring a boat”?`,
    `AI wrote me a love poem. My toaster now gets jealous.`,
    `The best political statement sometimes is just not attending the group chat.`,
    `“Be yourself” is great advice unless you're about to post unfiltered opinions at 2AM.`,
    `2025: Still waiting for teleportation. Still getting stuck in traffic behind a tractor.`,
    `Imagine explaining to your ancestors that you argue with strangers on a pocket rectangle every day.`,
    `Inspirational quote: You’ve survived 100% of your worst tweets. Keep going.`,
    `If karma was instant, online comment sections would be way shorter.`,
    `I trust horoscopes more than most economic forecasts. At least they’re honest about the chaos.`,
    `Weather app says “partly cloudy.” Sky looks like it’s auditioning for a disaster movie.`,
    `Elon bought what now? Can I buy a nap?`,
    `Reminder: You don’t have to attend every argument you’re invited to.`,
    `BREAKING: Gen Z reportedly not afraid of recession because “we’ve been broke since birth.”`,
    `Nothing screams adulthood like being excited about a new sponge.`,
    `I tried turning it off and back on again. It was me. I was the problem.`,
    `Waiting for my paycheck to hit like it’s the season finale of a drama series.`,
    `Why does every app want me to “enable notifications”? I barely enable myself.`,
    `Therapy is great but have you tried group-chat venting followed by memes?`,
    `Life tip: Never argue with someone who has Wi-Fi and nothing to lose.`,
    `I'm not saying I'm tired of capitalism, but I just bartered cookies for printer ink.`,
    `The news said “experts are concerned.” Bro, I’m concerned. Hire me.`,
    `Can we normalize slow success? I’m trying my best out here.`,
    `Woke up. Didn’t check Twitter. Touched grass. Felt peace. Highly recommend.`,
    `Astrologer: Mercury is in retrograde.
    Me: That explains everything, thank you.`,
    `Do I believe in miracles? I once found matching socks on a Monday.`,
    `Public service announcement: yelling at customer support never made anyone’s Wi-Fi faster.`,
    `There are two types of people: those who understand taxes and those who are me.`,
    `The new political strategy? Post a meme, then ghost.`,
    `Who needs a personality when you have good lighting and a cat?`,
    `My screen time report judged me harder than my own parents.`,
    `Just overheard someone say “I’m saving up for eggs.” We’re officially in dark times.`,
    `Me: I won’t spend anything today.
    Also me: *buys iced coffee the size of my soul*`,
    `“Stay positive,” they say. My bank account says otherwise.`,
    `Used to be scared of ghosts. Now I’m more afraid of job recruiters on LinkedIn.`,
    `Someone said “you are the average of your last 5 tweets.” Please no.`,
    `How is it that my emails never send when I’m productive, but send instantly when I regret it?`,
    `Advice: Vote, rest, hydrate, and avoid Facebook comments.`,
    `If Mondays were a person, I’d file a restraining order.`,
    `Plot twist: the group project that’s failing is democracy.`,
    `Just in: My dog is running for mayor. Campaign slogan: “More snacks, less drama.”`,
    `Honestly, we should be grading politicians like Uber drivers. “Kept promises: 2/5 stars.”`,
];
