name: Upload Website

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Build
      run: yarn install && yarn build

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./packages/live-streaming/dist/ s3://stream-peerchecker-com-dist --delete

    - name: Invalidate cache
      run: aws cloudfront create-invalidation --distribution-id E3FMW2ULSOH2AE --paths '/*';